# Generated by Django 4.0.4 on 2022-05-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_patient_daily_vitals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='daily_vitals',
        ),
    ]
