# Generated by Django 4.0.4 on 2022-05-19 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_patient_daily_vitals'),
        ('base', '0002_remove_dailyvitals_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyvitals',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.patient'),
        ),
    ]
